<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Markdig" />
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Ulid" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
  </ItemGroup>

</Project>
