<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>BlinkMark.ContractTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.OpenApi.Readers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlinkMark.Api\BlinkMark.Api.csproj" />
    <ProjectReference Include="..\..\src\BlinkMark.Preview\BlinkMark.Preview.csproj" />
    <ProjectReference Include="..\testhost\BlinkMark.TestHost.csproj" />
  </ItemGroup>

</Project>
